name: echopype
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - netCDF4
  - numpy
  - pynmea2
  - pytz
  - scipy
  - xarray
  - zarr
  # extras
  - beautifulsoup4
  - click
  - dask
  - ipykernel
  - pandas
  - requests
  - tox
